In [18]:
import pandas as pd
train_1 = pd.read_csv("tourist_ml.csv")
ratings=train_1.drop(['Unnamed: 0','ts','aspects','org_city','user_city'],axis=1)


ratings

                     user_id                org_id  rating
0        6777707737383161518   7184895086928047809     4.0
1       16897840124443804835   7184895086928047809     5.0
2        6643037495508673176   7184895086928047809     4.0
3       15204947921117401344   7184895086928047809     5.0
4        8757574242792609967  17298320470833172098     5.0
...                      ...                   ...     ...
129004    200375019925712923  15334747555863619226     4.0
129005   4093310282598233551  18027350004649392336     5.0
129006   6297481238260920238   1231488912766309557     5.0
129007   1036674189703071050    721952579178055276     5.0
129008   1846384429435549696   4617599458628286138     5.0

[129009 rows x 3 columns]

In [52]:
from surprise import Reader, Dataset

# to load dataset from pandas df, we need `load_fromm_df` method in surprise lib

ratings_dict = {'itemID': list(ratings.org_id),
                'userID': list(ratings.user_id),
                'rating': list(ratings.rating)}
df = pd.DataFrame(ratings_dict)

# A reader is still needed but only the rating_scale param is required.
# The Reader class is used to parse a file containing ratings.
reader = Reader(rating_scale=(4.0, 5.0))

# The columns must correspond to user id, item id and ratings (in that order).
data = Dataset.load_from_df(df[['userID', 'itemID', 'rating']], reader)

In [59]:

# Split data into 5 folds

#data.split(n_folds=5)

from surprise import SVD,SVDpp
from surprise import NMF,BaselineOnly,NormalPredictor,KNNWithZScore,SlopeOne,CoClustering
from surprise.model_selection import cross_validate
from surprise.model_selection import GridSearchCV



# nmf
#algo = NMF()
#cross_validate(algo, data, measures=['RMSE'], cv=5, verbose=True)
#evaluate(algo, data, measures=['RMSE'])

param_grid = {'n_epochs': [100, 150,200], 'lr_all': [0.002, 0.005],
              'reg_all': [0.6, 0.8]}
gs = GridSearchCV(SVD, param_grid, measures=['rmse', 'mae'], cv=3)

gs.fit(data)

# best RMSE score
print(gs.best_score['rmse'])

# combination of parameters that gave the best RMSE score
print(gs.best_params['rmse'])

0.3768438171749837
{'n_epochs': 100, 'lr_all': 0.002, 'reg_all': 0.6}

In [ ]:
# svd
algo = SVD()
cross_validate(algo, data, measures=['RMSE', 'MAE'], cv=5, verbose=True)
#evaluate(algo, data, measures=['RMSE'])

#BaselineOnly
algo = BaselineOnly()
cross_validate(algo, data, measures=['RMSE'], cv=5, verbose=True)


#NormalPredictor

algo = NormalPredictor()
cross_validate(algo, data, measures=['RMSE'], cv=5, verbose=True)

#SlopeOne

algo = SlopeOne()
cross_validate(algo, data, measures=['RMSE'], cv=5, verbose=True)

#SVDpp

algo = SVDpp()
cross_validate(algo, data, measures=['RMSE'], cv=5, verbose=True)

#CoClustering

algo = CoClustering()
cross_validate(algo, data, measures=['RMSE'], cv=5, verbose=True)